name: Cache-Clean

on:
  #仅手动清理缓存（已关闭定时清理）
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Cache Clean
        run: gh cache delete --all
